---

- hosts: servers
  tasks:
     - name: ensure nginx is latest version
       become: yes
       apt: name=nginx state=latest
     - name: start nginx
       service:
          name: nginx
          state: started
